# Generated by Django 3.0.3 on 2020-04-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_parameter', models.CharField(blank=True, max_length=256, null=True, verbose_name='Search Parameter')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Search Record',
                'verbose_name_plural': 'Search Records',
            },
        ),
    ]
