# Generated by Django 3.0.3 on 2020-04-05 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogModel',
        ),
    ]
