# Generated by Django 3.0.3 on 2021-07-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='total',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='rent_or_buy',
            field=models.CharField(choices=[('RNT', 'RENT'), ('BUY', 'BUY')], default='BUY', max_length=3),
        ),
    ]
