# Generated by Django 3.0.3 on 2021-07-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20210718_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='refundable',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
