# Generated by Django 3.0.3 on 2020-03-15 08:29

import corebookmodels.models
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Author Name', help_text='Please enter the name of a Author', max_length=100, verbose_name="Author's name")),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NoB', 'Non Binary'), ('Undef', 'Undefined')], default='Undef', max_length=12)),
                ('author_image', models.ImageField(blank=True, help_text='Upload Author image', null=True, upload_to=corebookmodels.models.upload_authorimage_path, verbose_name='Author Image')),
                ('dateOfBirth', models.DateField(help_text='Please enter the date when author was born', verbose_name="Author's Birth Day")),
                ('dateOfDeath', models.DateField(blank=True, help_text='Please enter the date when Author passed away.', null=True, verbose_name="Author's Death Date")),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='TO BAN THIS AUTHOR SELECT HERE', verbose_name='Ban Author?')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['name', 'dateOfBirth'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre', max_length=100, verbose_name='Name of the Genre')),
                ('is_active', models.BooleanField(default=True, help_text='Genre to be displayed to the user')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Nationality',
                'verbose_name_plural': 'Nationality',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Publication House Name')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title of Book')),
                ('book_image', models.ImageField(blank=True, help_text='Upload Book image', null=True, upload_to=corebookmodels.models.upload_bookimage_path, verbose_name='Book Image')),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('published_date', models.DateField(help_text='Enter the date when the book was published', verbose_name='Published Date')),
                ('number_of_pages', models.PositiveIntegerField(verbose_name='Number of pages')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, null=True, unique=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('author_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name_of_author', to='corebookmodels.Author')),
                ('book_genre', models.ManyToManyField(help_text='Select a genre for this book', related_name='genre_of_book', to='corebookmodels.Genre')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_of_book', to='corebookmodels.Language')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(help_text='Please all the books the author has written', related_name='books_by_author', to='corebookmodels.Book', verbose_name="Author's Books"),
        ),
        migrations.AddField(
            model_name='author',
            name='genre',
            field=models.ManyToManyField(help_text='Please add all the genre in which the Author writes', related_name='genre_by_author', to='corebookmodels.Genre', verbose_name="Author's Active Genre"),
        ),
        migrations.AddField(
            model_name='author',
            name='nationality',
            field=models.OneToOneField(help_text='Please enter the nationality of the Author', on_delete=django.db.models.deletion.CASCADE, related_name='author_nationality', to='corebookmodels.Nationality', verbose_name="Author's Nationality"),
        ),
        migrations.AddIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='corebookmod_search__72eaad_gin'),
        ),
    ]
