# Generated by Django 3.0.3 on 2020-04-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebookmodels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='team_name',
            field=models.CharField(default='BOOK', max_length=50),
        ),
    ]
