# Generated by Django 3.0.3 on 2020-09-14 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corebookmodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rental_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='corebookmodels.RentalCategory'),
        ),
    ]
