# Generated by Django 3.0.3 on 2020-04-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebookmodels', '0002_book_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='has_contest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
