# Generated by Django 3.0.3 on 2020-09-14 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corebookmodels', '0003_auto_20200915_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rental_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='corebookmodels.RentalCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='rental_price',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
