# Generated by Django 3.0.3 on 2020-09-14 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corebookmodels', '0004_auto_20200915_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rental_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='corebookmodels.RentalCategory'),
        ),
    ]
