# Generated by Django 3.0.3 on 2021-03-10 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corebookmodels', '0004_auto_20210310_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_category', to='corebookmodels.BookMainCategory'),
        ),
    ]
