# Generated by Django 3.0.3 on 2020-09-22 09:12

import corebookmodels.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corebookmodels', '0006_bookcategory_bookmaincategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcategory',
            options={'ordering': ['name'], 'verbose_name': 'Book Category', 'verbose_name_plural': 'Book Categories'},
        ),
        migrations.AlterModelOptions(
            name='bookmaincategory',
            options={'ordering': ['name'], 'verbose_name': 'Book Main Category', 'verbose_name_plural': 'Book Main Categories'},
        ),
        migrations.AddField(
            model_name='book',
            name='book_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='rental_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rentalcategory', to='corebookmodels.RentalCategory'),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='belongs_to',
            field=models.ForeignKey(default=11, on_delete=models.SET(corebookmodels.models.get_sentinel_book_category), related_name='main_category', to='corebookmodels.BookMainCategory'),
        ),
    ]
