# Generated by Django 3.0.3 on 2021-03-19 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corebookmodels', '0006_bookcategory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookBelongsTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('homepage_category', models.CharField(max_length=120, verbose_name='HomePage Category')),
                ('book_on_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corebookmodels.Book')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
