# Generated by Django 3.0.3 on 2021-03-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corebookmodels', '0007_bookbelongsto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookbelongsto',
            options={'verbose_name': 'HomePage Category', 'verbose_name_plural': 'HomePage Categories'},
        ),
        migrations.RemoveField(
            model_name='bookbelongsto',
            name='book_on_category',
        ),
    ]
