# Generated by Django 3.0.3 on 2021-03-19 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corebookmodels', '0008_auto_20210319_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='homepage_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='homepagecategory', to='corebookmodels.BookBelongsTo'),
        ),
    ]
