# Generated by Django 3.0.3 on 2020-09-24 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corebookmodels', '0008_auto_20200924_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookratingmodel',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='corebookmodels.Book'),
            preserve_default=False,
        ),
    ]
