# Generated by Django 3.0.3 on 2021-03-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebookmodels', '0009_book_homepage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookbelongsto',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
