# Generated by Django 3.0.3 on 2020-09-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebookmodels', '0009_bookratingmodel_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookratingmodel',
            options={'verbose_name': 'Book Rating', 'verbose_name_plural': 'Book Ratings'},
        ),
        migrations.AlterField(
            model_name='bookratingmodel',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
