# Generated by Django 3.0.3 on 2021-03-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebookmodels', '0010_bookbelongsto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='in_stock_buy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='in_stock_rent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookbelongsto',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
