# Generated by Django 3.0.3 on 2021-03-27 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corebookmodels', '0011_auto_20210324_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corebookmodels.BookMainCategory'),
        ),
    ]
