# Generated by Django 3.0.3 on 2021-07-18 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corebookmodels', '0012_book_book_main_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookRatingModel',
        ),
    ]
