# Generated by Django 3.0.3 on 2021-07-25 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corebookmodels', '0014_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corebookmodels.BookMainCategory'),
        ),
    ]
