# Generated by Django 3.0.3 on 2021-08-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corebookmodels', '0016_language_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['published_date']},
        ),
    ]
